### PR TITLE
trigger posix tests

### PR DESCRIPTION
**Pull request by dkarnikis**
Signed-off-by: Dimitris Karnikis <dkarnikis@gmail.com>

### CODE REVIEW

**Comment by dkarnikis** [comment]
@angelhof @nvasilakis @mgree I think the CI is ok. I will try to add some log functionality for posix tests

**Comment by dkarnikis** [comment]
To view the posix logs:
 ```sh
 # fetch the last 50 requests
 curl -s "ctrl.pash.ndr.md/job=fetch_runs&count=50" > dat.json`
 # find the hash we are interested in
 cat dat.json | jq -r '.rows | .[] | select(.commit=="3e44744f") | .tests' | jq . | jq -r '.[].posix_log'
```
 And it will print a dump of text :)
 
 @angelhof

**Comment by angelhof** [comment]
> To view the posix logs:
> 
> ```shell
> # fetch the last 50 requests
> curl -s "ctrl.pash.ndr.md/job=fetch_runs&count=50" > dat.json`
> # find the hash we are interested in
> cat dat.json | jq -r '.rows | .[] | select(.commit=="3e44744f") | .tests' | jq . | jq -r '.[].posix_log'
> ```
> 
> And it will print a dump of text :)

Great!

**Comment by mgree** [comment]
I don't know how GH actions does it, but can we store the resulting journal (or its summary) as a workflow artifact?

**Comment by dkarnikis** [comment]
> I don't know how GH actions does it, but can we store the resulting journal (or its summary) as a workflow artifact?

I can totally try that. This CI (running all the tests including posix), runs on every commit (on a PR). 
I think this might be an issue since a new artifact will be generated every time we push something on a branch.

Moreover, all the CI logs (of posix tests) are stored in a postgres database, thus we could fetch every single one of the stored entries (including commit hash/message/branch/date and journal log) using `curl` requests as shown in my previous message. What do you think about that?

**Comment by mgree** [comment]
That's fine, I suppose. An advantage of the artifacts is (a) backup on GH servers and (b) easy browsability. Postgres seems nice in that it'd be great to generate charts of conformance over time. I'm easy.

**Comment by dkarnikis** [comment]
The latest update builds and uploads a zip containing the execution logs(journal) of posix tests + the results of correctness tests.
The artifact is available when clicking on: 
1. POSIX-CI / issue-jobs (pull_request_target)
2. Summary (on bottom) 

OR by visiting the Actions Tab and finding the requested workflow

**Comment by mgree** [comment]
This is awesome, thank you for working it out!

**Pull request closed without merging**
