### PR TITLE
Dockerfile fix

### PR DESCRIPTION
**Pull request by dkarnikis**
- Remove `--depth` when cloning the repo in the containers
- Remove old file

Signed-off-by: Dimitris Karnikis <dkarnikis@gmail.com>

### CODE REVIEW

**Comment by tammam1998** [comment]
Hi Dimitris،
Whay is the reason for removing the depth argument?

**Comment by dkarnikis** [comment]
> Hi Dimitris، What is the reason for removing the depth argument?

In the current state, the user/developer is stuck at the main branch (due to depth) and cannot experiment with other branches (such as future)

**Comment by nvasilakis** [comment]
Ah, t's because `--depth` fetches the latest (not the full repo). Good idea. Curious, what's the difference in terms of execution time?

**Review by nvasilakis — APPROVED** [review]
Looks good to me, just make sure that the Docker-related`PASH_HOST` check has been changed appropriately everywhere.

**Pull request merged**
