### PR TITLE
add suggested command for installing packages on arch/manjaro

### PR DESCRIPTION
**Pull request by gulkily**
thanks

### CODE REVIEW

**Comment by angelhof** [comment]
@dkarnikis could you take care of merging that?

**Comment by dkarnikis** [comment]
@gulkily Thanks for the patch
Before merging the PR, could you fix your commit by signing it? Find more details [here](https://github.com/binpash/pash/pull/474/checks?check_run_id=5326713238).

Thanks!

**Review by nvasilakis — APPROVED** [review]
Awesome, thanks!

**Comment by dkarnikis** [comment]
Closed. `install.sh` is no longer supported

**Pull request closed without merging**
