### PR TITLE
CI/CD test parsing fixes. WIP

### PR DESCRIPTION
**Pull request by dkarnikis**

### CODE REVIEW

**Comment by nvasilakis** [comment]
We need to discuss the existence of both `PASH_FLAGS` and `-w` @dkarnikis @angelhof

**Comment by dkarnikis** [comment]
@nvasilakis  After the issue with `PASH_FLAGS` is resolved, I think we could merge the branch.

**Comment by nvasilakis** [comment]
> We need to discuss the existence of both `PASH_FLAGS` and `-w` @dkarnikis @angelhof

@angelhof: I am merging now to allow CI to run on the main branch, but when you have time please take a look!

**Review by nvasilakis — APPROVED** [review]
Great! (There are a few minor things to fix, but it's better if it's being battle-tested while we're fixing them:-)

**Comment by angelhof** [comment]
The PR looks good to me. I don't think there is any particular reason to have both `PASH_FLAGS` and `-w` in `run.par.sh`. I think they can be combined.

**Pull request merged**
