### PR TITLE
Port aggregators to FreeBSD

### PR DESCRIPTION
**Pull request by janekb04**
This PR is about porting aggregators to FreeBSD. Todo list (based on #277):
- [x] `wc` including `-lwcmL`
- [x] `uniq` including `-c` *required no changes*
- [x] `tr` including `-ctd`
- [x] `grep` including `-cEFGPefiwxsvoqaI` *required no changes*

Adding support for `sort` will come in a new PR.

### CODE REVIEW

**Comment by janekb04** [comment]
More PRs will be created from this branch later, so it shouldn't be deleted after merging.

**Comment by janekb04** [comment]
There is a difference between the Linux version of the `wc` command and the FreeBSD version. The Linux version treats the options `-m`  and `-c` separately and independently. On the FreeBSD version, however they are exclusive and [one cancels the other](https://www.freebsd.org/cgi/man.cgi?wc).

**Comment by nvasilakis** [comment]
Yes. Generally there are quite a few differences between BSD and Linux/GNU Coreutils. A easy way is to use `#ifdef`-style  conditional compilation (i.e. include one kind of functionality if in environment A, a different one if compiled in environment B.) Let me know if this makes sense.

**Comment by janekb04** [comment]
@nvasilakis I am currently finishing the conditional compilation. I am using a different approach though. Instead of using preprocessor directives inside the C++ files I will make the `Makefile` choose a different implementation based on the target system. There will be a separate `.h` file for an aggregator implementation for Linux and a separate file for BSD. If the implementations are the same, then the BSD version will simply consist of one line: `#include ../../linux/cmd/agg.h`.

**Comment by janekb04** [comment]
This one line will suffice. Even no include guards are necessary as the included file already has those and there is nothing else in the file to protect.

**Comment by nvasilakis** [comment]
That's a great idea, @janekb04 !

**Comment by janekb04** [comment]
@nvasilakis I was fighting for a while with the aggregators not wanting to compile on FreeBSD. It turned out that instead of using `make`, `gmake` has to be used. Does PaSh currently automatically use `gmake` on FreeBSD, or should I change PaSh to do so? I am asking because I know that other parts of PaSh also use Makefiles, so this problem would concern not only aggregators, and maybe should be in a different PR?

**Comment by janekb04** [comment]
At this point the `wc` agrregator mostly works on FreeBSD with the exception of some issues with padding. I will analyze [the `wc` source code for FreeBSD](https://github.com/freebsd/freebsd-src/blob/main/usr.bin/wc/wc.c) to investigate.

**Comment by janekb04** [comment]
`wc`, `uniq` and `grep` now work. `tr` is yet to be implemented.

**Comment by janekb04** [comment]
@nvasilakis All aggregators work on Linux and FreeBSD. PR ready for review.

**Comment by nvasilakis** [comment]
Awesome, @janekb04 — Will review and get back to you!

**Comment by janekb04** [comment]
@nvasilakis Thanks. I would also want to remind you, just in case, that I am leaving for the algorithmics "camp" next Monday and then writing the SAT, so I will be away until the end of August since then.

**Review by angelhof — APPROVED** [review]
This looks good. Something that we need to think about for the future is that we probably need to figure out a way to disambiguate between the bsd and linux commands in the annotation level too (and therefore by being different commands, their aggregators would be different).

**Comment by janekb04** [comment]
@angelhof The aggregators are always in the `runtime/agg/cpp/bin` directory. Their path doesn't change regardless of the host system, so I don't think that annotation files have to be platform specific.

**Comment by angelhof** [comment]
> @angelhof The aggregators are always in the `runtime/agg/cpp/bin` directory. Their path doesn't change regardless of the host system, so I don't think that annotation files have to be platform specific.

I agree that this is not an issue for aggregators. However, the flags do change behavior and that means that we need to have different annotations per platform. :)

**Comment by janekb04** [comment]
I have verified that aggregators can now compile on Clang including Apple Clang. After some non-extensive initial testing, it seems that in most cases the BSD aggregators seem to be working on macOS out of the box. There are some flags that didn't work yet, but I think that should be addressed by a new PR, so this one can get merged.

**Pull request merged**
