### PR TITLE
DSPaSh

### PR DESCRIPTION
**Pull request by tammam1998**
Distributed execution of shell files.

This PR contributes the following
- Compiler:  Infrastructure to execute bash scripts over a cluster of machines. This includes graph splitting, managing workers' load, distributing tasks while makings sure reads/writes to files/named pipes happen as if they were done locally.
- Runtime: An implementation for simple pipe over sockets to better control communication/socket behavior
- Additional flag --distributed_exec to the pash runtime
- Setup scripts to build runtime

This commit depends on changes in main that are not synced with future yet.

### CODE REVIEW

**Comment by nvasilakis** [comment]
@tammam1998 would it be best to review this together on Tuesday?

**Comment by angelhof** [comment]
Yes let's review together on Tuesday! We need to review both the new code, but also make sure that any changes to already existing PaSh code do not cause any issues :)

**Comment by tammam1998** [comment]
Added docs and removed changes unrelated to the PR. The PR is ready for merge

**Review by nvasilakis — APPROVED** [review]
Awesome work!<3

**Pull request merged**
