### PR TITLE
Correct tr in poets

### PR DESCRIPTION
**Pull request by nvasilakis**

### CODE REVIEW

**Review by dkarnikis — COMMENTED** [review]
Hey @nvasilakis, checking the author's code, the script he provides for finding `1-syllable words` is:
```
tr -sc ’[A-Z][a-z]’ ’[ 12*]’ < genesis |
grep -i ’ˆ[ˆaeiou]*[aeiou][ˆaeiou]*$’ |
sort | uniq -c | sed 5q
```

However, for finding `2-syllable` words he changes the `’[ 12*]’` to `’[\012*]’` .

I am not quite sure on how should we proceed.

**Comment by nvasilakis** [comment]
@dkarnikis Yeah, it's a mistake from the original author—the author was clearly trying to split into lines (as in `2-syllable` and other examples).

**Review by dkarnikis — APPROVED** [review]

**Review by angelhof — APPROVED** [review]
Does the updated code correspond to the original code written by the author or the opposite?

**Comment by nvasilakis** [comment]
> Does the updated code correspond to the original code written by the author or the opposite?

No, the original author clearly made a (tiny) mistake. There is a `\` missing.

**Pull request merged**
