### PR TITLE
Escaping unparsing issue

### PR DESCRIPTION
**Pull request by angelhof**

### CODE REVIEW

**Comment by angelhof** [comment]
@mgree if everything looks cool for now we can merge :)

**Comment by angelhof** [comment]
@dkarnikis can we figure out what fails in the Ubuntu 18 VM? Could it have to do with the python version in it (and some incompatibility with respect to this subprocess call `https://github.com/binpash/pash/blob/future/compiler/pash.py#L102`).

**Review by mgree — APPROVED** [review]
Looks good to me!

**Comment by angelhof** [comment]
@dkarnikis I found it, it had to do with the python version. I fixed it now to work starting from 3.6. Would there be any way to fix the python version in all testing instances to avoid such issues in the future?

**Comment by dkarnikis** [comment]
@angelhof sorry I was afk, I will try to solve this issue tomorrow (:

**Comment by angelhof** [comment]
No worries, I fixed the issue. The thing that we have to figure out is how to fix the python versions that we support and make sure that we only test for them (and not other ones depending on the Ubuntu version) :)

**Pull request merged**
